name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

env:
  IMAGE_NAME: responsive-html-email-templates

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Make image public
        run: |
          echo "Docker image built and pushed successfully!"
          echo "To make the image publicly accessible, please:"
          echo "1. Go to https://github.com/${{ github.repository_owner }}?tab=packages"
          echo "2. Find the '${{ env.IMAGE_NAME }}' package"
          echo "3. Click on Package settings"
          echo "4. Scroll down to 'Danger Zone' and click 'Change visibility'"
          echo "5. Select 'Public' and confirm"
          echo ""
          echo "Image is available at: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main"
